name: Upload Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
    - uses: actions/checkout@master
    - name: make
      run: make
    - name: Prepare ZIP
      run: mkdir exefs && cp Skyline600.nso exefs/subsdk1 && cp cross.npdm exefs/main.npdm && zip Skyline.zip exefs -r
    - name: Upload build artifact
      uses: actions/upload-artifact@v1
      with:
        name: zip
        path: Skyline.zip
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: zip
    - name: Upload Release
      uses: Genwald/create-release@eba889c
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: beta
        code: beta
        body: Beta built off of the latest code in the repository.
        prerelease: true
        recreate: true
        assets: zip/Skyline.zip:Skyline.zip:application/zip
